
<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/exibir.css">

    <title>Exibir</title>
</head>
<body>
    <div class="container">
            <h1>Exibir dados</h1>
            ⠀<a href="/register">Digite seus dados</a>
        </div>
        <H2>Resultados</h2>
        <?php 
        //Foreach($allUsers as $User) {
           // Echo $User['id_user'];
            //Echo $User['name_user'];
          //  }
          var_dump($allUsers);
            ?>
            


</div>

</body>
</html
