<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="public/css/login.css">
    <title>Login</title>
</head>
<body>
    <div class="container">
        <form class="login" action="login" method="POST">
            <h1>Login</h1>
            <input type="email" name="email" placeholder="Email" required>
            <input type="password" name="password" placeholder="Senha" required>
            <div class="flex">
                <input class="btn" type="submit" value="Entrar" required>
            </div>
            <p class="fontColor">Não tem conta?⠀<a href="/register">Cadastre-se</a></p>
        </form>
    </div>
</body>
</html>