<?php 
    use App\Models\UserDB;
?>

<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/registerDados.css">

    <title>Dados</title>
</head>
<body>
    <div class="container">
        
            <?php 
            if(!empty($error['emailError'])) {
                echo $error['emailError'];
            }
            ?>
        <form class="register" action="register/insert" method="POST">
            <h1>Dados</h1>
            <input type="email" name="email" placeholder="Email" required minlength="15" maxlength="100">
            <input type="text" name="username" placeholder="Nome" required minlength="3" maxlength="100">
            <input type="password" name="password" placeholder="senha mais usada" required minlength="6" maxlength="20">
            <div class="flex">
                <input class="btn" type="submit" value="Confirmar">
            </div>
            ⠀<a href="/exibir">Exibir Dados</a>
        </form>
    </div>
</body>
</html>